ALTER TABLE optical_devices
  ADD COLUMN IF NOT EXISTS total_ports   INTEGER,
  ADD COLUMN IF NOT EXISTS used_ports    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mikrotik_id   INTEGER REFERENCES mikrotik_routers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS technician_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS photo_url     TEXT;
